vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    dish_images:
      uri_prefix: /uploads
      upload_destination: '%kernel.project_dir%/public/uploads'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
